import './globals.css';
import { Luckiest_Guy } from 'next/font/google';

import Navbar from '@/components/Navbar';

const luckiestGuy = Luckiest_Guy({
  subsets: ['latin'],
  variable: '--font-luckiest-guy',
  weight: '400',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${luckiestGuy.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
